org.gradle.jvmargs=-Xmx3072m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true
android.nonTransitiveRClass=true
systemProp.http.socketTimeout=60000
systemProp.http.connectionTimeout=60000
systemProp.https.socketTimeout=60000
systemProp.https.connectionTimeout=60000
