import java.net.URI

plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("org.jetbrains.kotlin.plugin.serialization")
    id("com.google.dagger.hilt.android")
    id("com.google.devtools.ksp")
    id("io.gitlab.arturbosch.detekt")
    jacoco
}

fun validatedApiUrl(name: String, value: String, allowHttp: Boolean): String {
    val uri = URI(value)
    require(uri.isAbsolute && !uri.host.isNullOrBlank() && uri.rawUserInfo == null &&
        uri.rawQuery == null && uri.rawFragment == null &&
        (uri.path.isNullOrEmpty() || uri.path == "/")) {
        "$name must be an absolute origin without credentials/path/query/fragment"
    }
    require(uri.scheme == "https" || (allowHttp && uri.scheme == "http")) {
        "$name must use HTTPS${if (allowHttp) " or explicitly allowed local HTTP" else ""}"
    }
    if (uri.scheme == "http") {
        require(uri.host in setOf("localhost", "127.0.0.1", "10.0.2.2")) {
            "$name may use cleartext only for an explicit local development host"
        }
    }
    return value.trimEnd('/')
}

fun quoted(value: String): String = "\"${value.replace("\\", "\\\\").replace("\"", "\\\"")}\""

val devApiUrl = validatedApiUrl(
    "JARVIS_DEV_API_BASE_URL",
    providers.gradleProperty("JARVIS_DEV_API_BASE_URL").orElse("http://10.0.2.2:8080").get(),
    allowHttp = true
)
val stagingApiUrl = validatedApiUrl(
    "JARVIS_STAGING_API_BASE_URL",
    providers.gradleProperty("JARVIS_STAGING_API_BASE_URL")
        .orElse("https://staging-api.jarvis.ai").get(),
    allowHttp = false
)
val productionApiUrl = "https://api.jarvis.ai"
require(stagingApiUrl != productionApiUrl) { "Staging and production API origins must differ" }

// Экспорт схем Room в app/schemas — обязательно для миграций и MigrationTestHelper
// (см. JarvisMigrations.kt, пункт аудита #7).
ksp {
    arg("room.schemaLocation", "$projectDir/schemas")
}

android {
    namespace = "com.jarvis.assistant"
    compileSdk = 34

    defaultConfig {
        applicationId = "com.jarvis.assistant"
        minSdk = 29
        targetSdk = 34
        versionCode = 1
        versionName = "0.2.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary = true
        }

        // Этап 2: MediaPipe поставляет нативные библиотеки для 4 ABI
        // (arm64-v8a 26 МБ, armeabi-v7a 19 МБ, x86 32 МБ, x86_64 29 МБ).
        // Исключаем x86 — 32-битных x86-устройств и эмуляторов практически
        // не осталось; x86_64 оставляем ради эмулятора на CI/разработке.
        ndk {
            abiFilters += listOf("arm64-v8a", "armeabi-v7a", "x86_64")
        }
    }

    flavorDimensions += "environment"
    productFlavors {
        create("dev") {
            dimension = "environment"
            applicationIdSuffix = ".dev"
            versionNameSuffix = "-dev"
            buildConfigField("String", "JARVIS_API_BASE_URL", quoted(devApiUrl))
            buildConfigField("String", "JARVIS_LICENSE_BASE_URL", quoted(devApiUrl))
            buildConfigField("boolean", "ALLOW_CLEARTEXT_BACKEND", (devApiUrl.startsWith("http://")).toString())
            manifestPlaceholders["appLabel"] = "JARVIS Dev"
        }
        create("staging") {
            dimension = "environment"
            applicationIdSuffix = ".staging"
            versionNameSuffix = "-staging"
            buildConfigField("String", "JARVIS_API_BASE_URL", quoted(stagingApiUrl))
            buildConfigField("String", "JARVIS_LICENSE_BASE_URL", quoted(stagingApiUrl))
            buildConfigField("boolean", "ALLOW_CLEARTEXT_BACKEND", "false")
            manifestPlaceholders["appLabel"] = "JARVIS Staging"
        }
        create("prod") {
            dimension = "environment"
            buildConfigField("String", "JARVIS_API_BASE_URL", quoted(productionApiUrl))
            buildConfigField("String", "JARVIS_LICENSE_BASE_URL", quoted(productionApiUrl))
            buildConfigField("boolean", "ALLOW_CLEARTEXT_BACKEND", "false")
            manifestPlaceholders["appLabel"] = "JARVIS"
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
        debug {
            isMinifyEnabled = false
            // JVM coverage is available without a device. Instrumented coverage
            // is generated by create<Flavor>DebugCoverageReport on a real target.
            enableUnitTestCoverage = true
            enableAndroidTestCoverage = true
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }

    composeOptions {
        kotlinCompilerExtensionVersion = libs.versions.composeCompiler.get()
    }

    testOptions {
        unitTests {
            // android.util.Log и прочие android.jar-заглушки возвращают значения
            // по умолчанию вместо выброса "not mocked" в чистых JVM-тестах.
            isReturnDefaultValues = true
        }
    }

    testCoverage {
        jacocoVersion = "0.8.11"
    }

    // Lint blocks every new warning/error. The reviewed portable baseline has
    // 88 entries: 60 deferred dependency/tooling messages repeated per flavor
    // and 28 unchanged Android findings tracked in the dependency update plan.
    // The baseline must never be refreshed wholesale without reviewing its diff.
    lint {
        warningsAsErrors = true
        baseline = file("lint-baseline.xml")
        abortOnError = true
    }

    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
}

detekt {
    buildUponDefaultConfig = true
    allRules = false
    parallel = true
    basePath = rootProject.projectDir.absolutePath
    config.setFrom(rootProject.files("config/detekt/detekt.yml"))
}

tasks.withType<io.gitlab.arturbosch.detekt.Detekt>().configureEach {
    jvmTarget = "17"
    exclude("**/build/**", "**/generated/**")
    reports {
        html.required.set(true)
        xml.required.set(true)
        sarif.required.set(true)
        txt.required.set(false)
    }
}

extensions.configure<org.gradle.testing.jacoco.plugins.JacocoPluginExtension> {
    toolVersion = "0.8.11"
}

tasks.withType<Test>().configureEach {
    extensions.configure<org.gradle.testing.jacoco.plugins.JacocoTaskExtension> {
        isIncludeNoLocationClasses = true
        excludes = listOf("jdk.internal.*")
    }
}

val jacocoGeneratedCodeExcludes = listOf(
    "**/R.class",
    "**/R\$*.class",
    "**/BuildConfig.*",
    "**/Manifest*.*",
    "dagger/hilt/**",
    "hilt_aggregated_deps/**",
    "**/Dagger*.*",
    "**/*_Factory.*",
    "**/*_MembersInjector.*",
    "**/*_ComponentTreeDeps.*",
    "**/*_HiltComponents*.*",
    "**/*_HiltModules*.*",
    "**/Hilt_*.*",
    "**/*_Impl.*",
    "**/*\$Companion\$CREATOR*.*",
    "**/*\$\$serializer.*"
)

val jacocoDevDebugReport = tasks.register<org.gradle.testing.jacoco.tasks.JacocoReport>("jacocoDevDebugUnitTestReport") {
    group = "verification"
    description = "Runs devDebug JVM tests and creates JaCoCo XML/HTML/CSV reports."
    dependsOn("testDevDebugUnitTest")

    executionData.from(
        layout.buildDirectory.file(
            "outputs/unit_test_code_coverage/devDebugUnitTest/testDevDebugUnitTest.exec"
        )
    )
    sourceDirectories.from(files("src/main/java", "src/main/kotlin"))
    classDirectories.from(
        files(
            fileTree(layout.buildDirectory.dir("tmp/kotlin-classes/devDebug")) {
                exclude(jacocoGeneratedCodeExcludes)
            },
            fileTree(
                layout.buildDirectory.dir(
                    "intermediates/javac/devDebug/compileDevDebugJavaWithJavac/classes"
                )
            ) {
                exclude(jacocoGeneratedCodeExcludes)
            }
        )
    )
    reports {
        xml.required.set(true)
        html.required.set(true)
        csv.required.set(true)
        xml.outputLocation.set(layout.buildDirectory.file("reports/jacoco/devDebug/jacoco.xml"))
        html.outputLocation.set(layout.buildDirectory.dir("reports/jacoco/devDebug/html"))
        csv.outputLocation.set(layout.buildDirectory.file("reports/jacoco/devDebug/jacoco.csv"))
    }
}

tasks.register<org.gradle.testing.jacoco.tasks.JacocoCoverageVerification>(
    "jacocoDevDebugCoverageVerification"
) {
    group = "verification"
    description = "Rejects regression below the reviewed Phase 3 JVM coverage floor."
    dependsOn(jacocoDevDebugReport)
    executionData.from(jacocoDevDebugReport.map { it.executionData })
    classDirectories.from(jacocoDevDebugReport.map { it.classDirectories })
    violationRules {
        rule {
            limit {
                counter = "LINE"
                value = "COVEREDRATIO"
                minimum = "0.24".toBigDecimal()
            }
            limit {
                counter = "BRANCH"
                value = "COVEREDRATIO"
                minimum = "0.20".toBigDecimal()
            }
        }
    }
}

configurations.configureEach {
    if (!name.startsWith("detekt")) {
        // Kotlin 1.9 JVM/Android classes come from kotlin-stdlib. The legacy
        // common metadata artifact has no Android runtime variant; retaining it
        // makes AGP lint's artifact view disagree with strict dependency locks.
        exclude(group = "org.jetbrains.kotlin", module = "kotlin-stdlib-common")
    }

    resolutionStrategy.eachDependency {
        when {
            !this@configureEach.name.startsWith("detekt") &&
                requested.group == "org.jetbrains.kotlin" &&
                requested.name.startsWith("kotlin-stdlib") -> {
                useVersion("1.9.24")
                because("production and test classpaths must match the Kotlin 1.9.24 compiler metadata")
            }
            !this@configureEach.name.startsWith("detekt") &&
                requested.group == "org.jetbrains.kotlinx" &&
                requested.name.startsWith("kotlinx-coroutines") -> {
                useVersion("1.8.1")
                because("last reviewed coroutines line compatible with Kotlin 1.9.24")
            }
            requested.group == "androidx.compose.ui" &&
                requested.name.startsWith("ui-test") -> {
                useVersion("1.6.8")
                because("Compose UI tests must stay aligned with the Kotlin 1.9 Compose runtime")
            }
            requested.group == "io.netty" -> {
                useVersion("4.1.137.Final")
                because("security floor for 2025/2026 Netty codec and TLS CVEs")
            }
            requested.group == "com.google.protobuf" && requested.name == "protobuf-java" -> {
                useVersion("3.25.5")
                because("fix CVE-2024-7254 in Android test/build tooling")
            }
            requested.group == "com.google.protobuf" && requested.name == "protobuf-javalite" -> {
                useVersion("4.28.2")
                because("fix CVE-2024-7254 in MediaPipe runtime dependencies")
            }
            requested.group == "commons-io" && requested.name == "commons-io" -> {
                useVersion("2.14.0")
                because("fix CVE-2024-47554 in Android test tooling")
            }
            requested.group == "com.google.guava" && requested.name == "guava" -> {
                useVersion("33.7.1-android")
                because("remove CVE-2023-2976 and CVE-2020-8908 from Android tooling")
            }
        }
    }
}

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    implementation(libs.androidx.lifecycle.runtime.compose)
    implementation(libs.androidx.activity.compose)

    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.ui.graphics)
    implementation(libs.androidx.compose.ui.tooling.preview)
    implementation(libs.androidx.compose.material3)
    implementation(libs.androidx.compose.material.icons.extended)

    implementation(libs.androidx.navigation.compose)

    implementation(libs.hilt.android)
    ksp(libs.hilt.compiler)
    implementation(libs.androidx.hilt.navigation.compose)

    implementation(libs.androidx.room.runtime)
    implementation(libs.androidx.room.ktx)
    ksp(libs.androidx.room.compiler)

    implementation(libs.okhttp.core)
    implementation(libs.okhttp.logging)

    implementation(libs.kotlinx.serialization.json)
    implementation(libs.kotlinx.coroutines.core)
    implementation(libs.kotlinx.coroutines.android)

    // Этап 2 — Local AI: MediaPipe LLM Inference (on-device Gemma 3 1B).
    // Native libs увеличивают APK: ~26 МБ (arm64-v8a). Сама модель (~529 МБ)
    // в APK НЕ входит — см. docs/LOCAL_AI.md.
    implementation(libs.mediapipe.tasks.genai)

    implementation(libs.androidx.datastore.preferences)
    implementation(libs.androidx.security.crypto)

    testImplementation(libs.junit)
    testImplementation(libs.kotlinx.coroutines.test)
    testImplementation(libs.mockk)
    testImplementation(libs.okhttp.mockwebserver)

    // UI semantics tests run as Android instrumentation; Compose test coverage
    // is merged by createDevDebugCoverageReport when a device is connected.
    androidTestImplementation(libs.androidx.compose.ui.test.junit4)
    debugImplementation(libs.androidx.compose.ui.test.manifest)

    // Инструментальные тесты (androidTest): миграции Room, критичные потоки.
    androidTestImplementation(libs.androidx.room.testing)
    androidTestImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.androidx.test.core)
    androidTestImplementation(libs.androidx.test.runner)
}
